"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://test.4training.net
  name = test4training
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'test4training'
    langs = {
        'en': 'test.4training.net',
    }

    def scriptpath(self, code):
        return {
            'en': '/mediawiki',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
