@startuml

title CorrectBot class diagram

    CorrectBot -- Communicator: uses
    CorrectBot -- Corrector: uses
    Corrector -- ArabicCorrector: uses
    Corrector -- EnglishCorrector: uses
    Corrector -- FrenchCorrector: uses
    Corrector -- GermanCorrector: uses
    Corrector -- SpanishCorrector: uses

    package "Communicator" {
      Communicator -- PageWrapperPacker: uses
      Communicator -- PageWrapper: uses
      PageWrapperPacker -- PageWrapper: uses
      PageWrapperPacker -- ServerCommunicator: uses
      ServerCommunicator -- PyWikiBot: uses
    }

    package [PyWikiBot] << external >> #BBBBBB  {

    }

@enduml