@startuml

title Sequence diagram for CorrectBot

actor User
participant CorrectBot
participant Corrector
box "Communicator"
  participant Communicator
  participant PageWrapperPacker
  participant ServerCommunicator
end box
participant PyWikiBot
database MediaWiki

    User -> CorrectBot
    CorrectBot -> Communicator: create
    Communicator -> PageWrapperPacker: fetch_page_content_from_wiki()
    PageWrapperPacker -> ServerCommunicator: request_text_from_server()
    ServerCommunicator -> PyWikiBot: create Page-object
    PyWikiBot -> MediaWiki: request
    PyWikiBot <-- MediaWiki
    ServerCommunicator <-- PyWikiBot: Page-object
    alt #E9ECEF "Page-object exists"

      PageWrapperPacker <-- ServerCommunicator: PageWrapper-object
      Communicator <-- PageWrapperPacker
      CorrectBot <-- Communicator

      create Corrector
      CorrectBot -> Corrector:  create with PageWrapper

      Corrector -> Corrector: Correct typos
      CorrectBot <-- Corrector: Write fixes back to PageWrapper
      CorrectBot -> CorrectBot: print_diff()

      alt "Simulation mode active"
        CorrectBot -> Communicator
        Communicator -> PageWrapperPacker: save_page_content_to_wiki()
        PageWrapperPacker -> ServerCommunicator: send_text_to_server()
        ServerCommunicator -> PyWikiBot: create Page-object
        PyWikiBot -> MediaWiki: request
        PyWikiBot <-- MediaWiki
        ServerCommunicator <-- PyWikiBot: Page-object

        alt #E9ECEF "Page-object exists"
          ServerCommunicator -> PyWikiBot: save text to Page-object
          PyWikiBot -> MediaWiki
        else "Page-object does not exist"
          User <-- ServerCommunicator: Abort script
        end
      end

    else "Page-object does not exist"
      User <-- ServerCommunicator : Abort script
    end

@enduml